# prometheus-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
  selector:
    app: prometheus
