# grafana-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: grafana
